### ISSUE TITLE
导入的时候报错

### ISSUE THREAD

**Issue by long1318737396** [mYu4N/mytracer#1]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/116941376/217698943-c6bc97f9-6aac-41ff-aaf8-6db880fb3df8.png">

**Comment by mYu4N** [comment]
pip3 install bcc numba pytest 
python3 +4.1x的内核 当前存在兼容性问题，可能需要单独编译llvm，可以先用python2.x
python3+ alinux3 5.x的内核可以直接用
